version: '3.8'
services:
  postgres:
    build:
      context: .
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
    restart: always
